<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Wodsoft.UI.Gallery</RootNamespace>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\src\UniversalPresentationFramework.Platforms.Win32\UniversalPresentationFramework.Platforms.Win32.csproj" />
		<ProjectReference Include="..\UniversalPresentationFramework.Gallery\UniversalPresentationFramework.Gallery.csproj" />
	</ItemGroup>
</Project>
